In [1]:
#imports
import os
import pandas as pd
import numpy as np
import random
random.seed(1)

In [2]:
#read in the dataset (select 2015)
year = 'brfss_2023'
brfss_2023_dataset = pd.read_csv(f'{year}.csv')

In [3]:
#How many rows and columns
brfss_2023_dataset.shape

(183814, 350)

In [4]:
#check that the data loaded in is in the correct format
pd.set_option('display.max_columns', 500)
brfss_2023_dataset.head()

_STATE  FMONTH        IDATE IMONTH   IDAY    IYEAR  DISPCODE  \
0     1.0     1.0  b'03012023'  b'03'  b'01'  b'2023'    1100.0   
1     1.0     1.0  b'01062023'  b'01'  b'06'  b'2023'    1100.0   
2     1.0     1.0  b'03082023'  b'03'  b'08'  b'2023'    1100.0   
3     1.0     1.0  b'03062023'  b'03'  b'06'  b'2023'    1100.0   
4     1.0     1.0  b'01062023'  b'01'  b'06'  b'2023'    1100.0   

           SEQNO          _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  \
0  b'2023000001'  2.023000e+09       1.0       1.0       NaN       1.0   
1  b'2023000002'  2.023000e+09       1.0       1.0       NaN       1.0   
2  b'2023000003'  2.023000e+09       1.0       1.0       NaN       1.0   
3  b'2023000004'  2.023000e+09       1.0       1.0       NaN       1.0   
4  b'2023000005'  2.023000e+09       1.0       1.0       NaN       1.0   

   CELPHON1  LADULT1  NUMADULT  RESPSLC1  LANDSEX2  LNDSXBRT  SAFETIME  \
0       2.0      1.0       2.0       1.0       2.0       NaN       NaN   
1       2.0      1.0       1.0       NaN       2.0       NaN       NaN   
2       2.0      1.0       1.0       NaN       2.0       NaN       NaN   
3       2.0      1.0       2.0       1.0       2.0       NaN       NaN   
4       2.0      1.0       1.0       NaN       2.0       NaN       NaN   

   CTELNUM1  CELLFON5  CADULT1  CELLSEX2  CELSXBRT  PVTRESD3  CCLGHOUS  \
0       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
1       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
2       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
3       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
4       NaN       NaN      NaN       NaN       NaN       NaN       NaN   

   CSTATE1  LANDLINE  HHADULT  SEXVAR  GENHLTH  PHYSHLTH  MENTHLTH  POORHLTH  \
0      NaN       NaN      NaN     2.0      2.0      88.0      88.0       NaN   
1      NaN       NaN      NaN     2.0      2.0      88.0      88.0       NaN   
2      NaN       NaN      NaN     2.0      4.0       6.0       2.0       1.0   
3      NaN       NaN      NaN     2.0      2.0       2.0      88.0      88.0   
4      NaN       NaN      NaN     2.0      4.0      88.0      88.0       NaN   

   PRIMINS1  PERSDOC3  MEDCOST1  CHECKUP1  EXERANY2  EXRACT12  EXEROFT1  \
0       3.0       1.0       2.0       2.0       2.0       NaN       NaN   
1       3.0       1.0       2.0       2.0       1.0       1.0     106.0   
2       3.0       1.0       1.0       1.0       1.0       1.0     205.0   
3       3.0       1.0       2.0       3.0       1.0       1.0     103.0   
4       3.0       1.0       2.0       1.0       1.0       1.0     102.0   

   EXERHMM1  EXRACT22  EXEROFT2  EXERHMM2  STRENGTH  BPHIGH6  BPMEDS1  \
0       NaN       NaN       NaN       NaN     888.0      1.0      1.0   
1      30.0      88.0       NaN       NaN     888.0      1.0      2.0   
2      15.0      88.0       NaN       NaN     205.0      1.0      1.0   
3      30.0      88.0       NaN       NaN     888.0      3.0      NaN   
4      45.0       8.0     107.0     100.0     888.0      1.0      1.0   

   CHOLCHK3  TOLDHI3  CHOLMED3  CVDINFR4  CVDCRHD4  CVDSTRK3  ASTHMA3  \
0       3.0      2.0       2.0       2.0       2.0       2.0      2.0   
1       2.0      1.0       1.0       2.0       2.0       2.0      2.0   
2       2.0      1.0       1.0       2.0       2.0       2.0      1.0   
3       3.0      2.0       2.0       2.0       2.0       2.0      2.0   
4       2.0      2.0       2.0       2.0       2.0       2.0      2.0   

   ASTHNOW  CHCSCNC1  CHCOCNC1  CHCCOPD3  ADDEPEV3  CHCKDNY2  HAVARTH4  \
0      NaN       2.0       2.0       2.0       2.0       2.0       2.0   
1      NaN       2.0       2.0       2.0       1.0       2.0       1.0   
2      1.0       2.0       2.0       2.0       2.0       2.0       1.0   
3      NaN       1.0       1.0       2.0       1.0       2.0       1.0   
4      NaN       2.0       1.0       2.0       1.0       2.0       1.0   

   DIABETE

In [5]:
# select specific columns
brfss_df_selected = brfss_2023_dataset[['DIABETE4',
                                         '_RFHYPE6',  
                                         'TOLDHI3', 'CHOLCHK3', 
                                         '_BMI5', 
                                         'SMOKE100', 
                                         'CVDSTRK3', '_MICHD', 
                                         '_TOTINDA', 
                                         '_RFDRHV8', 
                                         '_HLTHPL1', 'MEDCOST1', 
                                         'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', 
                                         '_SEX', '_AGEG5YR', 'EDUCA', 'INCOME3' ]]

In [6]:
brfss_df_selected.shape

(183814, 20)

In [7]:
brfss_df_selected.head()

DIABETE4  _RFHYPE6  TOLDHI3  CHOLCHK3   _BMI5  SMOKE100  CVDSTRK3  _MICHD  \
0       1.0       2.0      2.0       3.0  3047.0       2.0       2.0     2.0   
1       3.0       2.0      1.0       2.0  2856.0       2.0       2.0     2.0   
2       3.0       2.0      1.0       2.0  2231.0       1.0       2.0     2.0   
3       3.0       1.0      2.0       3.0  2744.0       2.0       2.0     2.0   
4       1.0       2.0      2.0       2.0  2585.0       2.0       2.0     2.0   

   _TOTINDA  _RFDRHV8  _HLTHPL1  MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  \
0       2.0       1.0       1.0       2.0      2.0      88.0      88.0   
1       1.0       1.0       1.0       2.0      2.0      88.0      88.0   
2       1.0       1.0       1.0       1.0      4.0       2.0       6.0   
3       1.0       1.0       1.0       2.0      2.0      88.0       2.0   
4       1.0       1.0       1.0       2.0      4.0      88.0      88.0   

   DIFFWALK  _SEX  _AGEG5YR  EDUCA  INCOME3  
0       1.0   2.0      13.0    5.0     99.0  
1       2.0   2.0      13.0    5.0     99.0  
2       1.0   2.0      13.0    4.0      2.0  
3       1.0   2.0      12.0    5.0     99.0  
4       1.0   2.0      12.0    5.0      7.0

## CLEAN THE DATA

In [9]:
#Drop Missing Values - knocks 100,000 rows out right away
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(143774, 20)

In [10]:
# Reclassify DIABETE4 to match the new ordinal values:
# 0: No diabetes or only during pregnancy
# 1: Yes
# 2: Yes, but female told only during pregnancy
# 3: No
# 4: Pre-diabetes or borderline diabetes

# Replace the values in DIABETE4 column
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({
    1: 1,  # Yes
    2: 2,  # Yes, but female told only during pregnancy
    3: 3,  # No
    4: 4,  # Pre-diabetes or borderline diabetes
    0: 0   # No diabetes or only during pregnancy
})

# Remove rows with 'Don't know' (7) and 'Refused' (9)
brfss_df_selected = brfss_df_selected[~brfss_df_selected['DIABETE4'].isin([7, 9])]

# Verify the unique values in DIABETE4
print(brfss_df_selected['DIABETE4'].unique())

[1. 3. 2. 4.]


In [11]:
#1 _RFHYPE6
#Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
brfss_df_selected['_RFHYPE6'] = brfss_df_selected['_RFHYPE6'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE6 != 9]
brfss_df_selected._RFHYPE6.unique()

array([1., 0.])

In [12]:
#2 TOLDHI3
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['TOLDHI3'] = brfss_df_selected['TOLDHI3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 9]
brfss_df_selected.TOLDHI3.unique()

array([0., 1.])

In [40]:
#3 _CHOLCH3
# Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# Remove 9
brfss_df_selected['CHOLCHK3'] = brfss_df_selected['CHOLCHK3'].replace({3:0,2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CHOLCHK3 != 9]
brfss_df_selected.CHOLCHK3.unique()

array([0., 4., 8., 5., 6.])

In [41]:
#4 _BMI5 (no changes, just note that these are BMI * 100. So for example a BMI of 4018 is really 40.18)
brfss_df_selected['_BMI5'] = brfss_df_selected['_BMI5'].div(100).round(0)
brfss_df_selected._BMI5.unique()

array([ 22.,  26.,  30.,  33.,  23.,  42.,  24.,  28.,  29.,  27.,  36.,
        25.,  38.,  44.,  31.,  32.,  52.,  34.,  20.,  37.,  40.,  19.,
        35.,  46.,  41.,  47.,  21.,  43.,  17.,  49.,  18.,  45.,  39.,
        48.,  16.,  15.,  50.,  54.,  13.,  56.,  62.,  77.,  51.,  68.,
        53.,  55.,  67.,  70.,  14.,  57.,  59.,  58.,  66.,  60.,  65.,
        72.,  82.,  61.,  64.,  76.,  12.,  83.,  75.,  71.,  63.,  73.,
        74.,  84.,  69.,  87., 100.,  78.,  95.,  89.,  80.,  79.,  81.])

In [42]:
#5 SMOKE100
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([1., 0.])

In [43]:
#6 CVDSTRK3
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['CVDSTRK3'] = brfss_df_selected['CVDSTRK3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

array([0., 1.])

In [44]:
#7 _MICHD
#Change 2 to 0 because this means did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [45]:
#8 _TOTINDA
# 1 for physical activity
# change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([1., 0.])

In [46]:
#11 _RFDRHV8
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# remove all dont knows and missing 9
brfss_df_selected['_RFDRHV8'] = brfss_df_selected['_RFDRHV8'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV8 != 9]
brfss_df_selected._RFDRHV8.unique()

array([0.])

In [47]:
#12 _HLTHPL1
# 1 is yes, change 2 to 0 because it is No health care access
# remove 7 and 9 for don't know or refused
brfss_df_selected['_HLTHPL1'] = brfss_df_selected['_HLTHPL1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL1 != 9]
brfss_df_selected._HLTHPL1.unique()

array([1., 0.])

In [48]:
#13 MEDCOST1
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don/t know and 9 for refused
brfss_df_selected['MEDCOST1'] = brfss_df_selected['MEDCOST1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 9]
brfss_df_selected.MEDCOST1.unique()

array([1., 0.])

In [49]:
#14 GENHLTH
# This is an ordinal variable that I want to keep (1 is Excellent -> 5 is Poor)
# Remove 7 and 9 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([4., 3., 2., 1., 5.])

In [50]:
#15 MENTHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([ 2.,  0.,  3., 25., 10., 30., 20., 15.,  5., 12.,  1., 21.,  7.,
       14.,  4., 29.,  8., 16.,  6., 17.,  9., 28., 11., 18., 22., 24.,
       13., 27., 26., 19., 23.])

In [51]:
#16 PHYSHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([ 6.,  0.,  2.,  5.,  4., 21., 10., 25.,  7., 30., 20.,  3., 26.,
       14., 15.,  1.,  8., 24., 18., 13., 28., 16., 12., 17., 22., 27.,
       11.,  9., 29., 23., 19.])

In [52]:
#17 DIFFWALK
# change 2 to 0 for no. 1 is already yes
# remove 7 and 9 for don't know not sure and refused
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([1., 0.])

In [53]:
#18 SEX
# in other words - is respondent male (somewhat arbitrarily chose this change because men are at higher risk for heart disease)
# change 2 to 0 (female as 0). Male is 1
brfss_df_selected['_SEX'] = brfss_df_selected['_SEX'].replace({2:0})
brfss_df_selected._SEX.unique()

array([0., 1.])

In [54]:
#19 _AGEG5YR
# already ordinal. 1 is 18-24 all the way up to 13 wis 80 and older. 5 year increments.
# remove 14 because it is don't know or missing
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([13., 12.,  9.,  8., 10., 11.,  6.,  4.,  7.,  5.,  3.,  1.,  2.])

In [55]:
#20 EDUCA
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove 9 for refused:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([4., 5., 6., 3., 2., 1.])

In [56]:
#21 INCOME3
# Variable is already ordinal with 1 being less than $10,000 all the way up to 8 being $75,000 or more
# Remove 77 and 99 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 99]
brfss_df_selected.INCOME3.unique()

array([ 2.,  7.,  6.,  9.,  3.,  5.,  4.,  8., 11., 10.,  1.])

In [57]:
#Check the shape of the dataset now: We have 253,680 cleaned rows and 22 columns (1 of which is our dependent variable)
brfss_df_selected.shape

(110599, 20)

In [58]:
#Let's see what the data looks like after Modifying Values
brfss_df_selected.head()

DIABETE4  _RFHYPE6  TOLDHI3  CHOLCHK3  _BMI5  SMOKE100  CVDSTRK3  _MICHD  \
2       3.0       1.0      1.0       0.0   22.0       1.0       0.0     0.0   
4       1.0       1.0      0.0       0.0   26.0       0.0       0.0     0.0   
5       3.0       1.0      1.0       0.0   30.0       0.0       0.0     0.0   
8       3.0       1.0      1.0       0.0   33.0       0.0       0.0     0.0   
9       1.0       1.0      1.0       0.0   23.0       1.0       0.0     1.0   

   _TOTINDA  _RFDRHV8  _HLTHPL1  MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  \
2       1.0       0.0       1.0       1.0      4.0       2.0       6.0   
4       1.0       0.0       1.0       0.0      4.0       0.0       0.0   
5       1.0       0.0       1.0       0.0      3.0       3.0       2.0   
8       0.0       0.0       1.0       0.0      3.0       0.0       5.0   
9       1.0       0.0       1.0       0.0      3.0       0.0       0.0   

   DIFFWALK  _SEX  _AGEG5YR  EDUCA  INCOME3  
2       1.0   0.0      13.0    4.0      2.0  
4       1.0   0.0      12.0    5.0      7.0  
5       0.0   0.0       9.0    5.0      7.0  
8       1.0   0.0      13.0    5.0      6.0  
9       0.0   1.0      12.0    4.0      7.0

In [59]:
#Check Class Sizes of the heart disease column
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
1.0    16187
2.0      795
3.0    90735
4.0     2882
dtype: int64

In [60]:
#Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes_012', 
                                         '_RFHYPE6':'HighBP',  
                                         'TOLDHI3':'HighChol', 'CHOLCHK3':'CholCheck', 
                                         '_BMI5':'BMI', 
                                         'SMOKE100':'Smoker', 
                                         'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', 
                                         '_TOTINDA':'PhysActivity',
                                         '_RFDRHV8':'HvyAlcoholConsump', 
                                         '_HLTHPL1':'AnyHealthcare', 'MEDCOST1':'NoDocbcCost', 
                                         'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 
                                         '_SEX':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME3':'Income' })



In [61]:
brfss.head()

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
2           3.0     1.0       1.0        0.0  22.0     1.0     0.0   
4           1.0     1.0       0.0        0.0  26.0     0.0     0.0   
5           3.0     1.0       1.0        0.0  30.0     0.0     0.0   
8           3.0     1.0       1.0        0.0  33.0     0.0     0.0   
9           1.0     1.0       1.0        0.0  23.0     1.0     0.0   

   HeartDiseaseorAttack  PhysActivity  HvyAlcoholConsump  AnyHealthcare  \
2                   0.0           1.0                0.0            1.0   
4                   0.0           1.0                0.0            1.0   
5                   0.0           1.0                0.0            1.0   
8                   0.0           0.0                0.0            1.0   
9                   1.0           1.0                0.0            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
2          1.0      4.0       2.0       6.0       1.0  0.0  13.0        4.0   
4          0.0      4.0       0.0       0.0       1.0  0.0  12.0        5.0   
5          0.0      3.0       3.0       2.0       0.0  0.0   9.0        5.0   
8          0.0      3.0       0.0       5.0       1.0  0.0  13.0        5.0   
9          0.0      3.0       0.0       0.0       0.0  1.0  12.0        4.0   

   Income  
2     2.0  
4     7.0  
5     7.0  
8     6.0  
9     7.0

In [62]:
brfss.shape

(110599, 20)

In [63]:
#Check how many respondents have no diabetes, prediabetes or diabetes. Note the class imbalance!
brfss.groupby(['Diabetes_012']).size()

Diabetes_012
1.0    16187
2.0      795
3.0    90735
4.0     2882
dtype: int64

In [64]:
#************************************************************************************************
brfss.to_csv('diabetes_012_health_indicators_BRFSS2023.csv', sep=",", index=False)
#************************************************************************************************

## 5. Creating a Binary Dataset for Diabetes vs. No Diabetes
To create a binary classification dataset distinguishing diabetes from no diabetes, we can handle prediabetic individuals in one of three ways: grouping them with diabetics, grouping them with non-diabetics, or excluding them entirely. For this analysis, I propose grouping prediabetics with diabetics. A prediabetes diagnosis indicates a heightened risk of diabetes, aligning with our focus on understanding risk.

We can also balance the dataset into a 50-50 split between non-diabetics and the combined group of diabetics and prediabetics. There are enough records available to accomplish this randomly while maintaining predictive value. Specifically, we can combine the 0 prediabetic cases and 6,581 diabetic cases to form a group of 6,581 individuals at diabetes risk. This can be matched with 6,581 randomly selected non-diabetic cases from the 255,008 available.

It's important to note that, as this dataset is survey-based, some individuals may not yet have been diagnosed as prediabetic or diabetic, meaning undiagnosed cases could exist.

In [65]:
#Copy old table to new one.
brfss_binary = brfss
#Change the diabetics 2 to a 1 and pre-diabetics 1 to a 0, so that we have 0 meaning non-diabetic and pre-diabetic and 1 meaning diabetic.
brfss_binary['Diabetes_012'] = brfss_binary['Diabetes_012'].replace({1:0})
brfss_binary['Diabetes_012'] = brfss_binary['Diabetes_012'].replace({2:1})

#Change the column name to Diabetes_binary
brfss_binary = brfss_binary.rename(columns = {'Diabetes_012': 'Diabetes_binary'})
brfss_binary.Diabetes_binary.unique()

array([3., 0., 1., 4.])

In [66]:
#Show the change
brfss_binary.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
2              3.0     1.0       1.0        0.0  22.0     1.0     0.0   
4              0.0     1.0       0.0        0.0  26.0     0.0     0.0   
5              3.0     1.0       1.0        0.0  30.0     0.0     0.0   
8              3.0     1.0       1.0        0.0  33.0     0.0     0.0   
9              0.0     1.0       1.0        0.0  23.0     1.0     0.0   

   HeartDiseaseorAttack  PhysActivity  HvyAlcoholConsump  AnyHealthcare  \
2                   0.0           1.0                0.0            1.0   
4                   0.0           1.0                0.0            1.0   
5                   0.0           1.0                0.0            1.0   
8                   0.0           0.0                0.0            1.0   
9                   1.0           1.0                0.0            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
2          1.0      4.0       2.0       6.0       1.0  0.0  13.0        4.0   
4          0.0      4.0       0.0       0.0       1.0  0.0  12.0        5.0   
5          0.0      3.0       3.0       2.0       0.0  0.0   9.0        5.0   
8          0.0      3.0       0.0       5.0       1.0  0.0  13.0        5.0   
9          0.0      3.0       0.0       0.0       0.0  1.0  12.0        4.0   

   Income  
2     2.0  
4     7.0  
5     7.0  
8     6.0  
9     7.0

In [67]:
#show class sizes
brfss_binary.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    16187
1.0      795
3.0    90735
4.0     2882
dtype: int64

In [ ]:
# Separate the 0 (Non-diabetes) and 1 (Diabetes risk)
# Get the 1s (Diabetes risk group)
brfss_5050_1 = brfss_binary[brfss_binary['Diabetes_binary'] == 1]

# Get the 0s (Non-diabetes group)
brfss_5050_0 = brfss_binary[brfss_binary['Diabetes_binary'] == 0]

# Randomly select the same number of cases as the diabetes risk group (to balance classes)
num_diabetes_cases = len(brfss_5050_1)  # Get the number of cases in the diabetes risk group
brfss_5050_0_rand = brfss_5050_0.sample(n=num_diabetes_cases, random_state=42)

# Combine the sampled 0s and all 1s into a balanced dataset
brfss_5050 = pd.concat([brfss_5050_0_rand, brfss_5050_1], ignore_index=True)

# Verify the new balanced dataset
print(brfss_5050['Diabetes_binary'].value_counts())


Diabetes_binary
0.0    795
1.0    795
Name: count, dtype: int64


In [74]:
#Check that it worked. Now we have a dataset of 79,954 rows that is equally balanced with 50% 1 and 50% 0 for the target variable Diabetes_binary
brfss_5050.head()


Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        0.0  52.0     1.0     0.0   
1              0.0     0.0       1.0        0.0  32.0     1.0     0.0   
2              0.0     1.0       1.0        0.0  33.0     0.0     0.0   
3              0.0     0.0       1.0        0.0  27.0     1.0     0.0   
4              0.0     1.0       1.0        0.0  29.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  HvyAlcoholConsump  AnyHealthcare  \
0                   1.0           1.0                0.0            1.0   
1                   0.0           1.0                0.0            1.0   
2                   1.0           1.0                0.0            1.0   
3                   1.0           1.0                0.0            1.0   
4                   0.0           1.0                0.0            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      4.0       1.0       0.0       0.0  0.0   9.0        5.0   
1          0.0      2.0       3.0       2.0       0.0  1.0   6.0        6.0   
2          0.0      3.0       3.0      10.0       1.0  1.0  11.0        6.0   
3          0.0      4.0      20.0      20.0       1.0  1.0  11.0        4.0   
4          0.0      2.0       0.0       0.0       0.0  1.0  11.0        6.0   

   Income  
0     7.0  
1     9.0  
2     6.0  
3     2.0  
4     8.0

In [75]:

brfss_5050.tail()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
1585              1.0     1.0       1.0        0.0  36.0     1.0     0.0   
1586              1.0     1.0       0.0        0.0  27.0     0.0     0.0   
1587              1.0     1.0       1.0        0.0  30.0     1.0     0.0   
1588              1.0     1.0       0.0        0.0  22.0     0.0     0.0   
1589              1.0     1.0       1.0        0.0  32.0     0.0     0.0   

      HeartDiseaseorAttack  PhysActivity  HvyAlcoholConsump  AnyHealthcare  \
1585                   0.0           1.0                0.0            1.0   
1586                   0.0           1.0                0.0            1.0   
1587                   0.0           1.0                0.0            1.0   
1588                   0.0           1.0                0.0            1.0   
1589                   0.0           1.0                0.0            1.0   

      NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
1585          0.0      4.0      10.0      30.0       1.0  0.0   5.0   
1586          0.0      3.0       0.0      30.0       0.0  0.0  13.0   
1587          0.0      2.0       0.0       0.0       0.0  0.0  10.0   
1588          0.0      2.0       5.0       1.0       0.0  0.0   7.0   
1589          0.0      2.0       0.0      30.0       0.0  0.0   8.0   

      Education  Income  
1585        4.0     6.0  
1586        5.0     8.0  
1587        5.0     7.0  
1588        6.0     9.0  
1589        6.0     9.0

In [76]:
#See the classes are perfectly balanced now
brfss_5050.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    795
1.0    795
dtype: int64

In [77]:
# Reclassify the Diabetes_binary column
brfss_binary['Diabetes_binary'] = brfss_binary['Diabetes_binary'].replace({
    0: 0,  # No diabetes or only during pregnancy
    3: 0,  # No
    4: 1,  # Pre-diabetes or borderline diabetes
    1: 2,  # Yes
    2: 2   # Yes, but female told only during pregnancy
})

# Verify the unique values and their counts
print(brfss_binary['Diabetes_binary'].value_counts())


Diabetes_binary
0.0    106922
1.0      2882
2.0       795
Name: count, dtype: int64


In [80]:
# Separate the 0s (No diabetes), 1s (Pre-diabetes), and 2s (Diabetes)
brfss_0 = brfss_binary[brfss_binary['Diabetes_binary'] == 0]
brfss_1 = brfss_binary[brfss_binary['Diabetes_binary'] == 1]
brfss_2 = brfss_binary[brfss_binary['Diabetes_binary'] == 2]

# Balance the dataset (if needed, e.g., 50-50 split for modeling)
# Here, balancing the non-diabetes (0) with the diabetes-risk group (1 and 2 combined)
diabetes_risk_group = pd.concat([brfss_1, brfss_2])
num_diabetes_cases = len(diabetes_risk_group)

# Randomly sample from the non-diabetes group to match the size of the diabetes-risk group
brfss_0_sample = brfss_0.sample(n=num_diabetes_cases, random_state=42)

# Combine into a balanced dataset
brfss_5050 = pd.concat([brfss_0_sample, diabetes_risk_group], ignore_index=True)

# Verify the balanced dataset
print(brfss_5050['Diabetes_binary'].value_counts())


Diabetes_binary
0.0    3677
1.0    2882
2.0     795
Name: count, dtype: int64


In [81]:
#Check that it worked. Now we have a dataset of 79,954 rows that is equally balanced with 50% 1 and 50% 0 for the target variable Diabetes_binary
brfss_5050.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     0.0       1.0        0.0  29.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  32.0     0.0     0.0   
2              0.0     1.0       1.0        0.0  28.0     1.0     0.0   
3              0.0     0.0       0.0        4.0  21.0     0.0     0.0   
4              0.0     1.0       0.0        0.0  27.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  HvyAlcoholConsump  AnyHealthcare  \
0                   0.0           1.0                0.0            1.0   
1                   0.0           1.0                0.0            1.0   
2                   1.0           1.0                0.0            1.0   
3                   0.0           0.0                0.0            0.0   
4                   0.0           1.0                0.0            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      3.0       1.0       2.0       0.0  1.0   6.0        4.0   
1          0.0      3.0       5.0       7.0       1.0  0.0   5.0        6.0   
2          0.0      3.0       0.0       0.0       0.0  1.0  11.0        5.0   
3          0.0      3.0       0.0       0.0       0.0  0.0   4.0        5.0   
4          0.0      3.0       1.0       0.0       0.0  1.0   8.0        6.0   

   Income  
0     6.0  
1    11.0  
2     6.0  
3     4.0  
4     9.0

In [82]:
brfss_5050.tail()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
7349              2.0     1.0       1.0        0.0  36.0     1.0     0.0   
7350              2.0     1.0       0.0        0.0  27.0     0.0     0.0   
7351              2.0     1.0       1.0        0.0  30.0     1.0     0.0   
7352              2.0     1.0       0.0        0.0  22.0     0.0     0.0   
7353              2.0     1.0       1.0        0.0  32.0     0.0     0.0   

      HeartDiseaseorAttack  PhysActivity  HvyAlcoholConsump  AnyHealthcare  \
7349                   0.0           1.0                0.0            1.0   
7350                   0.0           1.0                0.0            1.0   
7351                   0.0           1.0                0.0            1.0   
7352                   0.0           1.0                0.0            1.0   
7353                   0.0           1.0                0.0            1.0   

      NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
7349          0.0      4.0      10.0      30.0       1.0  0.0   5.0   
7350          0.0      3.0       0.0      30.0       0.0  0.0  13.0   
7351          0.0      2.0       0.0       0.0       0.0  0.0  10.0   
7352          0.0      2.0       5.0       1.0       0.0  0.0   7.0   
7353          0.0      2.0       0.0      30.0       0.0  0.0   8.0   

      Education  Income  
7349        4.0     6.0  
7350        5.0     8.0  
7351        5.0     7.0  
7352        6.0     9.0  
7353        6.0     9.0

In [83]:
#See the classes are perfectly balanced now
brfss_5050.groupby(['Diabetes_binary']).size()


Diabetes_binary
0.0    3677
1.0    2882
2.0     795
dtype: int64

In [84]:
print(f'brfss_5050={brfss_5050.shape}',f'brfss_binary={brfss_binary.shape}')

brfss_5050=(7354, 20) brfss_binary=(110599, 20)


In [85]:
#Save the 50-50 balanced dataset to csv
#************************************************************************************************
brfss_5050.to_csv('diabetes_binary_5050split_health_indicators_BRFSS2023.csv', sep=",", index=False)
#************************************************************************************************

#Also save the original binary dataset to csv
#************************************************************************************************
brfss_binary.to_csv('diabetes_binary_health_indicators_BRFSS2023.csv', sep=",", index=False)
#************************************************************************************************